DROP DATABASE IF EXISTS tokens;

CREATE DATABASE IF NOT EXISTS tokens;

USE tokens;

CREATE TABLE IF NOT EXISTS email_tokens (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100),
  token VARCHAR(50) 
);